version: '3.8'

services:
  threejs-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./public:/usr/src/app/public
      - ./server.js:/usr/src/app/server.js
    environment:
      - NODE_ENV=development
    command: node server.js  # nodemonの代わりにnodeを使用
    restart: unless-stopped